CREATE TABLE IF NOT EXISTS movies (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        tmdb_id BIGINT NOT NULL UNIQUE,
                        title VARCHAR(255) NOT NULL,
                        original_title VARCHAR(255),
                        release_year INTEGER,
                        popularity DOUBLE PRECISION,
                        poster_path VARCHAR(255)
);